"""initial schema with interview domain

Revision ID: 241f969e16cb
Revises: 
Create Date: 2026-09-10 14:55:01.573861
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

revision: str = '241f969e16cb'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('jti', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replaced_by_jti', sa.String(length=128), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_jti'), 'refresh_tokens', ['jti'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('resumes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('parsed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_index(op.f('ix_resumes_user_id'), 'resumes', ['user_id'], unique=False)
    op.create_table('interviews',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('resume_id', sa.Uuid(), nullable=True),
    sa.Column('target_role', sa.String(length=255), nullable=False),
    sa.Column('programming_language', sa.String(length=128), nullable=True),
    sa.Column('interview_type', sa.String(length=32), nullable=False),
    sa.Column('difficulty', sa.String(length=32), nullable=False),
    sa.Column('interviewer_persona', sa.String(length=32), nullable=False),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('current_question_index', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('current_question_index >= 0', name='ck_interviews_current_index_nonneg'),
    sa.CheckConstraint('total_questions >= 1 AND total_questions <= 50', name='ck_interviews_total_questions_range'),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interviews_resume_id'), 'interviews', ['resume_id'], unique=False)
    op.create_index(op.f('ix_interviews_status'), 'interviews', ['status'], unique=False)
    op.create_index('ix_interviews_user_created', 'interviews', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_interviews_user_id'), 'interviews', ['user_id'], unique=False)
    op.create_index('ix_interviews_user_status', 'interviews', ['user_id', 'status'], unique=False)
    op.create_table('resume_analyses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('resume_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=255), nullable=False),
    sa.Column('target_role', sa.String(length=255), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('skills', sa.Text(), nullable=False),
    sa.Column('years_experience', sa.String(length=255), nullable=True),
    sa.Column('education', sa.Text(), nullable=True),
    sa.Column('gaps', sa.Text(), nullable=True),
    sa.Column('strengths', sa.Text(), nullable=True),
    sa.Column('suggested_focus_areas', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_analyses_resume_id'), 'resume_analyses', ['resume_id'], unique=False)
    op.create_table('interview_feedback',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('interview_id', sa.Uuid(), nullable=False),
    sa.Column('strengths', sa.Text(), nullable=True),
    sa.Column('areas_for_improvement', sa.Text(), nullable=True),
    sa.Column('detailed_feedback', sa.Text(), nullable=True),
    sa.Column('feedback_detail', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_feedback_interview_id'), 'interview_feedback', ['interview_id'], unique=True)
    op.create_table('interview_questions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('interview_id', sa.Uuid(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('question_type', sa.String(length=32), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('question_metadata', sa.JSON(), nullable=True),
    sa.Column('current_answer_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('order_index >= 0', name='ck_question_order_nonneg'),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('interview_id', 'order_index', name='uq_question_interview_order')
    )
    op.create_index(op.f('ix_interview_questions_interview_id'), 'interview_questions', ['interview_id'], unique=False)
    op.create_index('ix_questions_interview_order', 'interview_questions', ['interview_id', 'order_index'], unique=False)
    op.create_table('performance_reports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('interview_id', sa.Uuid(), nullable=False),
    sa.Column('technical_score', sa.Integer(), nullable=False),
    sa.Column('communication_score', sa.Integer(), nullable=False),
    sa.Column('overall_score', sa.Integer(), nullable=False),
    sa.Column('total_questions_answered', sa.Integer(), nullable=False),
    sa.Column('report_detail', sa.JSON(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('communication_score >= 0 AND communication_score <= 100', name='ck_report_communication_range'),
    sa.CheckConstraint('overall_score >= 0 AND overall_score <= 100', name='ck_report_overall_range'),
    sa.CheckConstraint('technical_score >= 0 AND technical_score <= 100', name='ck_report_technical_range'),
    sa.CheckConstraint('total_questions_answered >= 0', name='ck_report_answered_nonneg'),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_performance_reports_interview_id'), 'performance_reports', ['interview_id'], unique=True)
    op.create_table('answers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=False),
    sa.Column('time_taken_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('attempt_number >= 1', name='ck_answer_attempt_positive'),
    sa.ForeignKeyConstraint(['question_id'], ['interview_questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id', 'attempt_number', name='uq_answer_question_attempt')
    )
    op.create_index('ix_answers_question_attempt', 'answers', ['question_id', 'attempt_number'], unique=False)
    op.create_index(op.f('ix_answers_question_id'), 'answers', ['question_id'], unique=False)
    op.create_table('answer_evaluations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('answer_id', sa.Uuid(), nullable=False),
    sa.Column('correctness_score', sa.Integer(), nullable=False),
    sa.Column('relevance_score', sa.Integer(), nullable=False),
    sa.Column('completeness_score', sa.Integer(), nullable=False),
    sa.Column('technical_depth_score', sa.Integer(), nullable=False),
    sa.Column('technical_overall', sa.Integer(), nullable=False),
    sa.Column('clarity_score', sa.Integer(), nullable=False),
    sa.Column('structure_score', sa.Integer(), nullable=False),
    sa.Column('conciseness_score', sa.Integer(), nullable=False),
    sa.Column('communication_overall', sa.Integer(), nullable=False),
    sa.Column('evaluation_detail', sa.JSON(), nullable=True),
    sa.Column('evaluated_by', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('clarity_score >= 0 AND clarity_score <= 10', name='ck_eval_clarity_range'),
    sa.CheckConstraint('communication_overall >= 0 AND communication_overall <= 10', name='ck_eval_comm_overall_range'),
    sa.CheckConstraint('completeness_score >= 0 AND completeness_score <= 10', name='ck_eval_completeness_range'),
    sa.CheckConstraint('conciseness_score >= 0 AND conciseness_score <= 10', name='ck_eval_conciseness_range'),
    sa.CheckConstraint('correctness_score >= 0 AND correctness_score <= 10', name='ck_eval_correctness_range'),
    sa.CheckConstraint('relevance_score >= 0 AND relevance_score <= 10', name='ck_eval_relevance_range'),
    sa.CheckConstraint('structure_score >= 0 AND structure_score <= 10', name='ck_eval_structure_range'),
    sa.CheckConstraint('technical_depth_score >= 0 AND technical_depth_score <= 10', name='ck_eval_depth_range'),
    sa.CheckConstraint('technical_overall >= 0 AND technical_overall <= 10', name='ck_eval_tech_overall_range'),
    sa.ForeignKeyConstraint(['answer_id'], ['answers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_answer_evaluations_answer_id'), 'answer_evaluations', ['answer_id'], unique=True)
    op.create_table('interview_follow_ups',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('parent_question_id', sa.Uuid(), nullable=False),
    sa.Column('triggering_answer_id', sa.Uuid(), nullable=True),
    sa.Column('follow_up_text', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('follow_up_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['parent_question_id'], ['interview_questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['triggering_answer_id'], ['answers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_follow_ups_parent_question_id'), 'interview_follow_ups', ['parent_question_id'], unique=False)
    op.create_index(op.f('ix_interview_follow_ups_triggering_answer_id'), 'interview_follow_ups', ['triggering_answer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interview_follow_ups_triggering_answer_id'), table_name='interview_follow_ups')
    op.drop_index(op.f('ix_interview_follow_ups_parent_question_id'), table_name='interview_follow_ups')
    op.drop_table('interview_follow_ups')
    op.drop_index(op.f('ix_answer_evaluations_answer_id'), table_name='answer_evaluations')
    op.drop_table('answer_evaluations')
    op.drop_index(op.f('ix_answers_question_id'), table_name='answers')
    op.drop_index('ix_answers_question_attempt', table_name='answers')
    op.drop_table('answers')
    op.drop_index(op.f('ix_performance_reports_interview_id'), table_name='performance_reports')
    op.drop_table('performance_reports')
    op.drop_index('ix_questions_interview_order', table_name='interview_questions')
    op.drop_index(op.f('ix_interview_questions_interview_id'), table_name='interview_questions')
    op.drop_table('interview_questions')
    op.drop_index(op.f('ix_interview_feedback_interview_id'), table_name='interview_feedback')
    op.drop_table('interview_feedback')
    op.drop_index(op.f('ix_resume_analyses_resume_id'), table_name='resume_analyses')
    op.drop_table('resume_analyses')
    op.drop_index('ix_interviews_user_status', table_name='interviews')
    op.drop_index(op.f('ix_interviews_user_id'), table_name='interviews')
    op.drop_index('ix_interviews_user_created', table_name='interviews')
    op.drop_index(op.f('ix_interviews_status'), table_name='interviews')
    op.drop_index(op.f('ix_interviews_resume_id'), table_name='interviews')
    op.drop_table('interviews')
    op.drop_index(op.f('ix_resumes_user_id'), table_name='resumes')
    op.drop_table('resumes')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_jti'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
