"""answer idempotency keys

Revision ID: ed695e15ff26
Revises: 241f969e16cb
Create Date: 2026-09-10 15:11:30.844244
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

revision: str = 'ed695e15ff26'
down_revision: str | None = '241f969e16cb'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('answer_idempotency_keys',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('interview_id', sa.Uuid(), nullable=False),
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('answer_id', sa.Uuid(), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['answer_id'], ['answers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['interview_questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'interview_id', 'idempotency_key', name='uq_answer_idem_user_interview_key')
    )
    op.create_index(op.f('ix_answer_idempotency_keys_interview_id'), 'answer_idempotency_keys', ['interview_id'], unique=False)
    op.create_index(op.f('ix_answer_idempotency_keys_question_id'), 'answer_idempotency_keys', ['question_id'], unique=False)
    op.create_index(op.f('ix_answer_idempotency_keys_user_id'), 'answer_idempotency_keys', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_answer_idempotency_keys_user_id'), table_name='answer_idempotency_keys')
    op.drop_index(op.f('ix_answer_idempotency_keys_question_id'), table_name='answer_idempotency_keys')
    op.drop_index(op.f('ix_answer_idempotency_keys_interview_id'), table_name='answer_idempotency_keys')
    op.drop_table('answer_idempotency_keys')
    # ### end Alembic commands ###
